### ISSUE TITLE
asset division and multiplication

### ISSUE THREAD

**Issue by YaroShkvorets** [EOS-Nation/eos-common#16]
Divisor/multiplier parameters in `asset:times()` and `asset:div()` are converted to BigInteger, so something like `asset("100.0000 EOS").times(0.3)` will produce "0.0000 EOS"

https://github.com/EOS-Nation/eos-common/blob/cda9906763b396ad29c844c6ff4b60262ba115dd/eosiolib/asset.ts#L179-L180

We can either throw if parameter is not an integer or we can multiply it by some large number like `10^symbol.precision()` before operation and then divide the result by that same number.

**Comment by DenisCarriere** [comment]
Solution to divide fractions using BigInteger

```ts
asset("100.0000 EOS").times(3000).div(10000)
//=>'30.0000 EOS'
```
