### ISSUE TITLE
ExtendedSymbol&ExtendedAsset JSON string format

### ISSUE THREAD

**Issue by Avm07** [EOS-Nation/eos-common#25]
For passing ExtendedSymbol&ExtendedAsset in action data it requires JSON string format, current to_string() methods do not allow passing this data type to action JSON. But the to_string() method is correct for representing the type. Just need to add one more method for representation as a JSON string.

Current to_string() method, error then passing to action:
<img width="1365" alt="Снимок экрана 2022-06-04 в 17 15 25" src="https://user-images.githubusercontent.com/24969602/172006259-89a091e9-3a2f-4326-bdde-c8b3ac6d93e5.png">

Correct representing:
<img width="943" alt="Снимок экрана 2022-06-04 в 17 18 20" src="https://user-images.githubusercontent.com/24969602/172006263-7aab8ff3-8f7c-4e00-8a02-9a686a149602.png">

Same for ExtendedAsset, correct representing for action is {"quantity": "1.0000 EOS", "contract": "eosio.token"}

**Comment by DenisCarriere** [comment]
Added JSON support for `extended_symbol` & `extended_asset`

**extended_symbol**
```ts
const ext_sym = extended_symbol({contract: "eosio.token", sym: "4,EOS"});
const { contract, sym } = ext_sym.toJSON();
```

**extended_asset**
```ts
const ext_asset = extended_asset({contract: "eosio.token", quantity: "1.0000 EOS"});
const { contract, quantity } = ext_asset.toJSON();
```
