### ISSUE TITLE
Set max value to 2^48-1

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/eos-common#27]
### Question:

> Any idea have to prevent overflow crash if user type big values? It's converted to asset correct but after apply some times math result is overflow max possible value.

### Solution:

Enforce max value to 2^48-1

**Comment by Avm07** [comment]
I realize that its not issue of the lib, lib should follow similar data types implementation as in eosio.cdt so max value for asset is correct: 
`   static constexpr int64_t max_amount = (1LL << 62) - 1;
`

dApps should enforce max values to 2^48-1 for manual inputs for example to avoid overflow asserts, etc.
