### ISSUE TITLE
Bug invalid max magnitude check

### ISSUE THREAD

**Issue by Avm07** [EOS-Nation/eos-common#28]
Asset class does not allow me to init max allowed amount object

Example:

```javascript
var eosCommon = require("eos-common")

var tmp = new eosCommon.Asset('4611686018427387903 LPD');

Error: magnitude of asset amount must be less than 2^62
```

Correct statement that it should be less or equal to Asset::max_amount

The mistake is here in constructor from string:
https://github.com/EOS-Nation/eos-common/blob/master/eosiolib/asset.ts#L60

Number( amount_str ) <--- this cause current bug

```javascipt
var tst1 = new Number('4611686018427387903');
//Result tst1 = 4611686018427388000
```

Using Number constructor will cause round up of value and it will trigger the assert

**Comment by DenisCarriere** [comment]
@Avm07 thanks for the issue report.

The Asset string conversion was in fact causing an issue

Published solution in v0.11.0

**Comment by DenisCarriere** [comment]
https://runkit.com/deniscarriere/62db0fd589904e0008710974

**Comment by DenisCarriere** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/550895/180568158-1ea81c6b-3762-40d1-b2af-d8bc9f4677cd.png">
