### ISSUE TITLE
asset.plus() issue when using passing int values

### ISSUE THREAD

**Issue by gaboesquivel** [EOS-Nation/eos-common#9]
Hi @DenisCarriere 

This lib is great. thanks! I found this bug but I don't have the time to fix it right now, maybe later.. 

Best

![image](https://user-images.githubusercontent.com/391270/104095068-76e22b00-525a-11eb-8438-d51383656d5e.png)

**Comment by YaroShkvorets** [comment]
I think it works as expected here, treating 1000 as amount.

**Comment by DenisCarriere** [comment]
Correct

`1000`=`0.1000 EOS`

You are missing the 4 decimals

You are looking for:

```javascript
.plus(10000000)
```
